// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phjpyojetgxfsmqhhjfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoanB5b2pldGd4ZnNtcWhoamZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzcyMjksImV4cCI6MjA2MzY1MzIyOX0.W2gBRO2qsN8ovjObVcaojLazKzeUcPfUHQDgNw3KDg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);